services:
  Tweetcord:
    build: .
    image: ghcr.io/yuuzi261/tweetcord:0.6
    container_name: tweetcord
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./data/:/bot/data
      - ./configs.yml:/bot/configs.yml