# https://docs.docker.com/build/ci/github-actions/manage-tags-labels/

name: "Deploy docker image"

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Which tag to build'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate tag from release
        id: meta_release
        if: github.event_name == 'release'
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/username/app
          tags: |
            type=semver,pattern={{version}}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ (github.event_name == 'release' && steps.meta_release.outputs.tags) || format('ghcr.io/yuuzi261/tweetcord:{0}', github.event.inputs.tag) }}
          labels: ${{ steps.meta_release.outputs.labels }}